name: Build luci-app-kidcontrol

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build OpenWrt luci-app-kidcontrol
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential libncurses5-dev gawk git gettext libssl-dev \
          xsltproc zlib1g-dev unzip python3 python3-venv file

    - name: Clone OpenWrt source
      run: |
        mkdir -p openwrt
        cd openwrt
        git clone --depth=1 https://github.com/openwrt/openwrt.git .
        git checkout main

    - name: Prepare feeds (skip video feed to avoid errors)
      run: |
        cd openwrt
        sed -i '/src-git video/d' feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy luci-app-kidcontrol package
      run: |
        mkdir -p openwrt/package/luci-app-kidcontrol
        cp -r luci-app-kidcontrol/* openwrt/package/luci-app-kidcontrol/

    - name: Ensure LuCI framework dependencies
      run: |
        cd openwrt
        dep=$(grep '^LUCI_DEPENDS:=' package/luci-app-kidcontrol/Makefile | sed 's/LUCI_DEPENDS:=//')
        if [ ! -z "$dep" ]; then
          for pkg in $dep; do
            ./scripts/feeds install -p ${pkg%% *} -a
          done
        fi

    - name: Build luci-app-kidcontrol IPK
      run: |
        cd openwrt
        # 避免 ncurses menuconfig 报错
        export TERM=dumb
        make package/luci-app-kidcontrol/compile V=s

    - name: Generate version tag
      id: tag
      run: |
        VERSION="v$(date +'%Y.%m.%d.%H%M')"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        name: ${{ env.VERSION }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload IPK to Release
      uses: softprops/action-gh-release@v1
      with:
        files: openwrt/bin/targets/mediatek/filogic/packages/luci-app-kidcontrol_*.ipk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
