name: Build luci-app-kidcontrol

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build OpenWrt luci-app-kidcontrol
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up OpenWrt build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc zlib1g-dev unzip python3 python3-distutils file

    - name: Clone OpenWrt source
      run: |
        mkdir -p openwrt
        cd openwrt
        git clone --depth=1 https://github.com/openwrt/openwrt.git .
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy luci-app-kidcontrol package
      run: |
        mkdir -p openwrt/package/luci-app-kidcontrol
        cp -r ./* openwrt/package/luci-app-kidcontrol/

    - name: Build luci-app-kidcontrol IPK
      run: |
        cd openwrt
        make menuconfig  # 可选手动配置
        # 只编译 luci-app-kidcontrol，避免编译全部固件
        make package/luci-app-kidcontrol/compile V=s

    - name: Upload compiled IPK
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-kidcontrol
        path: openwrt/bin/targets/mediatek/filogic/packages/luci-app-kidcontrol_*.ipk
